# Generated by Django 3.2.18 on 2023-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, null=True)),
                ('ph_no', models.CharField(max_length=11)),
                ('car_no', models.CharField(max_length=10)),
                ('stall_no', models.IntegerField()),
                ('stake_no', models.IntegerField(null=True)),
                ('entry_no', models.IntegerField(null=True)),
                ('exit_no', models.IntegerField(null=True)),
                ('start_park_time', models.DateTimeField(null=True)),
                ('end_park_time', models.DateTimeField(null=True)),
                ('start_charge_time', models.DateTimeField(null=True)),
                ('finish_charge_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(null=True)),
                ('finish_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_row', models.IntegerField()),
                ('p_col', models.IntegerField()),
                ('stake_no', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('ph_no', models.CharField(max_length=11)),
                ('car_no', models.CharField(max_length=10, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.CharField(max_length=11)),
                ('car_no', models.CharField(max_length=10)),
                ('ip_no', models.CharField(default='0.0.0.0', max_length=16)),
            ],
        ),
    ]
